name: My Responsive Website Template
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Website
        run: |
          npm install
	  npm run build
          gem install jekyll
    	# Build situs web menggunakan Jekyll
    	jekyll build
     	./custom-build-script.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./xodervyn/DevOps1_201111265
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
